image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - golang.go
    - esbenp.prettier-vscode
tasks:
  - name: Dev Setup
    before: npm install --global netlify-cli
    init: yarn install
    command: ntl dev
